import type {
  Prospect,
  Campaign,
  Message,
  ActivityLog,
  Nicho,
  ScoreEtiqueta,
  ProspectEstado,
  ActivityTipo,
} from "@/types"

// ── Prospectos de ejemplo ─────────────────────────────────────

export const MOCK_PROSPECTS: Prospect[] = [
  {
    id: "p1",
    nombre_empresa: "Climatizaciones Martínez SL",
    nicho: "climatizacion",
    direccion: "Calle Mayor 12, Madrid",
    email: "info@climatizacionesmartinez.es",
    telefono: "+34 912 345 678",
    contacto_nombre: "Carlos Martínez",
    contacto_cargo: "Director General",
    web: "https://climatizacionesmartinez.es",
    valoracion_google: 4.6,
    num_resenas: 127,
    score_ia: 9.2,
    score_etiqueta: "Alta",
    score_justificacion: "Empresa activa con web profesional, 127 reseñas positivas, categoría exacta del nicho objetivo. Director General identificado como contacto directo.",
    estado: "interesado",
    notas: "Pidió ver demo en detalle",
    campaign_id: "c1",
    created_at: "2026-03-10T10:00:00Z",
    updated_at: "2026-03-22T14:30:00Z",
  },
  {
    id: "p2",
    nombre_empresa: "Instalaciones Técnicas Rodríguez",
    nicho: "instalaciones",
    direccion: "Av. de la Constitución 45, Sevilla",
    email: "contacto@instrodriguez.com",
    telefono: "+34 954 123 456",
    contacto_nombre: "Ana Rodríguez",
    contacto_cargo: "Responsable Técnica",
    web: "https://instrodriguez.com",
    valoracion_google: 4.3,
    num_resenas: 89,
    score_ia: 8.4,
    score_etiqueta: "Alta",
    score_justificacion: "Empresa de instalaciones con buena presencia digital, más de 80 reseñas y valoración alta. Contacto técnico identificado, perfil ideal para demo de partes.",
    estado: "contactado",
    notas: null,
    campaign_id: "c2",
    created_at: "2026-03-12T09:00:00Z",
    updated_at: "2026-03-20T11:00:00Z",
  },
  {
    id: "p3",
    nombre_empresa: "AireClima BCN",
    nicho: "climatizacion",
    direccion: "Carrer de Balmes 230, Barcelona",
    email: "admin@aireclima.cat",
    telefono: "+34 933 456 789",
    contacto_nombre: null,
    contacto_cargo: null,
    web: "https://aireclima.cat",
    valoracion_google: 4.8,
    num_resenas: 215,
    score_ia: 8.7,
    score_etiqueta: "Alta",
    score_justificacion: "Excelente valoración (4.8) con 215 reseñas, web propia y categoría exacta. No se dispone de contacto directo, lo que reduce ligeramente la puntuación.",
    estado: "respondio",
    notas: "Respondió al email con interés",
    campaign_id: "c1",
    created_at: "2026-03-11T08:30:00Z",
    updated_at: "2026-03-21T16:45:00Z",
  },
  {
    id: "p4",
    nombre_empresa: "Energía Solar del Sur",
    nicho: "energia",
    direccion: "Polígono Industrial Los Olivos, Málaga",
    email: "comercial@energiasur.es",
    telefono: "+34 952 789 012",
    contacto_nombre: "Miguel Fernández",
    contacto_cargo: "Director Comercial",
    web: "https://energiasur.es",
    valoracion_google: 4.1,
    num_resenas: 45,
    score_ia: 7.3,
    score_etiqueta: "Media",
    score_justificacion: "Empresa de energía solar con web y contacto directo. Valoración aceptable pero volumen de reseñas moderado. Encaje probable con el producto de gestión energética.",
    estado: "sin_contactar",
    notas: null,
    campaign_id: "c3",
    created_at: "2026-03-15T12:00:00Z",
    updated_at: "2026-03-15T12:00:00Z",
  },
  {
    id: "p5",
    nombre_empresa: "Fontanería Hermanos López",
    nicho: "instalaciones",
    direccion: "Calle del Prado 8, Valencia",
    email: "hlopez@fontanerialopez.com",
    telefono: "+34 963 111 222",
    contacto_nombre: "Javier López",
    contacto_cargo: "Gerente",
    web: null,
    valoracion_google: 3.9,
    num_resenas: 32,
    score_ia: 5.1,
    score_etiqueta: "Media",
    score_justificacion: "Empresa del sector instalaciones pero sin web propia. Pocas reseñas y valoración justa. El gerente está identificado, lo que mejora ligeramente el perfil.",
    estado: "sin_contactar",
    notas: null,
    campaign_id: "c2",
    created_at: "2026-03-16T14:00:00Z",
    updated_at: "2026-03-16T14:00:00Z",
  },
  {
    id: "p6",
    nombre_empresa: "Climavent Sistemas",
    nicho: "climatizacion",
    direccion: "Paseo de la Castellana 90, Madrid",
    email: "info@climavent.es",
    telefono: "+34 911 222 333",
    contacto_nombre: "Laura Sánchez",
    contacto_cargo: "Directora de Operaciones",
    web: "https://climavent.es",
    valoracion_google: 4.7,
    num_resenas: 178,
    score_ia: 9.5,
    score_etiqueta: "Alta",
    score_justificacion: "Empresa de climatización premium con excelente presencia digital, alta valoración y gran volumen de reseñas. Contacto de dirección identificado. Prospecto prioritario.",
    estado: "demo_enviada",
    notas: "Demo enviada el 18/03. Seguimiento pendiente.",
    campaign_id: "c1",
    created_at: "2026-03-08T10:00:00Z",
    updated_at: "2026-03-18T09:00:00Z",
  },
  {
    id: "p7",
    nombre_empresa: "Talleres Metálicos Gómez",
    nicho: "instalaciones",
    direccion: "Calle Industria 15, Zaragoza",
    email: "taller@metalicogomez.es",
    telefono: "+34 976 333 444",
    contacto_nombre: null,
    contacto_cargo: null,
    web: null,
    valoracion_google: 3.2,
    num_resenas: 11,
    score_ia: 3.4,
    score_etiqueta: "Baja",
    score_justificacion: "Sin web ni contacto directo. Pocas reseñas y valoración baja. Encaje dudoso con el producto de partes de instalaciones.",
    estado: "descartado",
    notas: "No encaja con el perfil objetivo",
    campaign_id: null,
    created_at: "2026-03-14T11:00:00Z",
    updated_at: "2026-03-14T11:30:00Z",
  },
  {
    id: "p8",
    nombre_empresa: "EcoEficiencia Energética",
    nicho: "energia",
    direccion: "Ronda de Atocha 22, Madrid",
    email: "info@ecoeficiencia.es",
    telefono: "+34 910 555 666",
    contacto_nombre: "Patricia Ruiz",
    contacto_cargo: "CEO",
    web: "https://ecoeficiencia.es",
    valoracion_google: 4.5,
    num_resenas: 67,
    score_ia: 8.1,
    score_etiqueta: "Alta",
    score_justificacion: "Empresa especializada en eficiencia energética con web profesional y CEO identificada. Buen volumen de reseñas positivas. Encaje alto con gestión energética A360.",
    estado: "contactado",
    notas: null,
    campaign_id: "c3",
    created_at: "2026-03-13T09:30:00Z",
    updated_at: "2026-03-19T10:00:00Z",
  },
  {
    id: "p9",
    nombre_empresa: "Frío Industrial Levante",
    nicho: "climatizacion",
    direccion: "Polígono Fuente del Jarro, Paterna, Valencia",
    email: "ventas@frioindustrial.es",
    telefono: "+34 961 777 888",
    contacto_nombre: "Roberto Navarro",
    contacto_cargo: "Jefe de Ventas",
    web: "https://frioindustrial.es",
    valoracion_google: 4.4,
    num_resenas: 93,
    score_ia: 7.8,
    score_etiqueta: "Media",
    score_justificacion: "Empresa de frío industrial, segmento ligeramente diferente al de conductos residenciales. Buena presencia digital y contacto comercial directo. Encaje probable.",
    estado: "contactado",
    notas: null,
    campaign_id: "c1",
    created_at: "2026-03-12T15:00:00Z",
    updated_at: "2026-03-20T08:30:00Z",
  },
  {
    id: "p10",
    nombre_empresa: "Reformas y Mantenimiento Gil",
    nicho: "otro",
    direccion: "Calle San Fernando 5, Bilbao",
    email: "info@reformasgil.com",
    telefono: "+34 944 999 000",
    contacto_nombre: null,
    contacto_cargo: null,
    web: null,
    valoracion_google: 2.8,
    num_resenas: 7,
    score_ia: 1.5,
    score_etiqueta: "Descartar",
    score_justificacion: "Empresa generalista de reformas, fuera del sector objetivo. Sin web, pocas reseñas y valoración baja. No recomendado para contacto.",
    estado: "descartado",
    notas: null,
    campaign_id: null,
    created_at: "2026-03-14T11:00:00Z",
    updated_at: "2026-03-14T11:00:00Z",
  },
]

// ── Campañas de ejemplo ───────────────────────────────────────

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "c1",
    nombre: "Climatización Madrid-BCN — Q1 2026",
    nicho: "climatizacion",
    canal: "email",
    template_id: "t1",
    score_minimo: 7.0,
    estado: "activa",
    fecha_inicio: "2026-03-01",
    fecha_fin: "2026-03-31",
    created_at: "2026-02-28T10:00:00Z",
    updated_at: "2026-03-01T08:00:00Z",
  },
  {
    id: "c2",
    nombre: "Instalaciones — Nacional",
    nicho: "instalaciones",
    canal: "ambos",
    template_id: "t2",
    score_minimo: 5.0,
    estado: "activa",
    fecha_inicio: "2026-03-10",
    fecha_fin: "2026-04-10",
    created_at: "2026-03-09T10:00:00Z",
    updated_at: "2026-03-10T08:00:00Z",
  },
  {
    id: "c3",
    nombre: "Energía — Piloto A360",
    nicho: "energia",
    canal: "email",
    template_id: "t3",
    score_minimo: 7.5,
    estado: "borrador",
    fecha_inicio: null,
    fecha_fin: null,
    created_at: "2026-03-15T10:00:00Z",
    updated_at: "2026-03-15T10:00:00Z",
  },
]

// ── Mensajes de ejemplo ───────────────────────────────────────

export const MOCK_MESSAGES: Message[] = [
  {
    id: "m1",
    prospect_id: "p1",
    campaign_id: "c1",
    canal: "email",
    asunto: "Una herramienta hecha para empresas de climatización como la tuya",
    contenido: "Hola Carlos, he desarrollado una aplicación específica para empresas de climatización...",
    estado_envio: "abierto",
    fecha_envio: "2026-03-15T10:30:00Z",
    fecha_respuesta: "2026-03-17T09:15:00Z",
    created_at: "2026-03-15T10:00:00Z",
  },
  {
    id: "m2",
    prospect_id: "p2",
    campaign_id: "c2",
    canal: "email",
    asunto: "Solución digital para la gestión de partes de instalaciones",
    contenido: "Estimada Ana, me dirijo a usted para presentarle una solución diseñada específicamente...",
    estado_envio: "entregado",
    fecha_envio: "2026-03-18T11:00:00Z",
    fecha_respuesta: null,
    created_at: "2026-03-18T10:45:00Z",
  },
  {
    id: "m3",
    prospect_id: "p3",
    campaign_id: "c1",
    canal: "email",
    asunto: "Una herramienta hecha para empresas de climatización como la tuya",
    contenido: "Hola, he desarrollado una aplicación específica para empresas de climatización...",
    estado_envio: "abierto",
    fecha_envio: "2026-03-14T09:00:00Z",
    fecha_respuesta: "2026-03-16T14:20:00Z",
    created_at: "2026-03-14T08:30:00Z",
  },
  {
    id: "m4",
    prospect_id: "p6",
    campaign_id: "c1",
    canal: "email",
    asunto: "Demo de gestión de conductos para Climavent",
    contenido: "Hola Laura, tras nuestra conversación, te envío el acceso a la demo...",
    estado_envio: "abierto",
    fecha_envio: "2026-03-18T09:00:00Z",
    fecha_respuesta: null,
    created_at: "2026-03-18T08:45:00Z",
  },
  {
    id: "m5",
    prospect_id: "p1",
    campaign_id: "c1",
    canal: "whatsapp",
    asunto: null,
    contenido: "Hola Carlos, te envío el enlace directo a la demo de gestión de partes de conductos...",
    estado_envio: "enviado",
    fecha_envio: "2026-03-20T16:00:00Z",
    fecha_respuesta: null,
    created_at: "2026-03-20T15:50:00Z",
  },
  {
    id: "m6",
    prospect_id: "p8",
    campaign_id: "c3",
    canal: "email",
    asunto: "Plataforma de gestión energética — Demo disponible",
    contenido: "Hola Patricia, he desarrollado una plataforma de gestión energética...",
    estado_envio: "entregado",
    fecha_envio: "2026-03-19T10:00:00Z",
    fecha_respuesta: null,
    created_at: "2026-03-19T09:45:00Z",
  },
]

// ── Activity log de ejemplo ───────────────────────────────────

export const MOCK_ACTIVITY: ActivityLog[] = [
  {
    id: "a1",
    prospect_id: "p1",
    tipo: "estado",
    descripcion: "Climatizaciones Martínez pasó a \"Interesado\" — pidió ver demo en detalle",
    created_at: "2026-03-22T14:30:00Z",
  },
  {
    id: "a2",
    prospect_id: "p3",
    tipo: "respuesta",
    descripcion: "AireClima BCN respondió al email con interés en la demo de conductos",
    created_at: "2026-03-21T16:45:00Z",
  },
  {
    id: "a3",
    prospect_id: "p1",
    tipo: "whatsapp",
    descripcion: "WhatsApp enviado a Climatizaciones Martínez con enlace a demo",
    created_at: "2026-03-20T16:00:00Z",
  },
  {
    id: "a4",
    prospect_id: "p9",
    tipo: "email",
    descripcion: "Email enviado a Frío Industrial Levante — campaña Climatización Madrid-BCN",
    created_at: "2026-03-20T08:30:00Z",
  },
  {
    id: "a5",
    prospect_id: "p8",
    tipo: "email",
    descripcion: "Email enviado a EcoEficiencia Energética — campaña Energía Piloto A360",
    created_at: "2026-03-19T10:00:00Z",
  },
  {
    id: "a6",
    prospect_id: "p6",
    tipo: "estado",
    descripcion: "Climavent Sistemas pasó a \"Demo enviada\" — acceso enviado por email",
    created_at: "2026-03-18T09:00:00Z",
  },
  {
    id: "a7",
    prospect_id: "p2",
    tipo: "email",
    descripcion: "Email enviado a Instalaciones Técnicas Rodríguez — campaña Instalaciones Nacional",
    created_at: "2026-03-18T11:00:00Z",
  },
  {
    id: "a8",
    prospect_id: "p1",
    tipo: "scoring",
    descripcion: "Scoring IA completado para Climatizaciones Martínez — 9.2/10 (Alta)",
    created_at: "2026-03-10T10:05:00Z",
  },
  {
    id: "a9",
    prospect_id: "p6",
    tipo: "scoring",
    descripcion: "Scoring IA completado para Climavent Sistemas — 9.5/10 (Alta)",
    created_at: "2026-03-08T10:05:00Z",
  },
  {
    id: "a10",
    prospect_id: "p5",
    tipo: "scoring",
    descripcion: "Scoring IA completado para Fontanería Hermanos López — 5.1/10 (Media)",
    created_at: "2026-03-16T14:05:00Z",
  },
]

// ── Helpers para estadísticas del dashboard ────────────────────

export function getMockStats() {
  const total = MOCK_PROSPECTS.length
  const respondieron = MOCK_PROSPECTS.filter((p) => ["respondio", "interesado", "demo_enviada", "cerrado"].includes(p.estado)).length
  const interesados = MOCK_PROSPECTS.filter((p) => ["interesado", "demo_enviada", "cerrado"].includes(p.estado)).length
  const demos = MOCK_PROSPECTS.filter((p) => ["demo_enviada", "cerrado"].includes(p.estado)).length

  return { total, respondieron, interesados, demos }
}

export function getMockFunnelData() {
  const counts: Record<string, number> = {}
  for (const p of MOCK_PROSPECTS) {
    counts[p.estado] = (counts[p.estado] || 0) + 1
  }
  return [
    { label: "Sin contactar", value: counts["sin_contactar"] || 0, color: "bg-slate-500" },
    { label: "Contactados", value: counts["contactado"] || 0, color: "bg-blue-500" },
    { label: "Respondieron", value: counts["respondio"] || 0, color: "bg-indigo-500" },
    { label: "Interesados", value: counts["interesado"] || 0, color: "bg-amber-500" },
    { label: "Demo enviada", value: counts["demo_enviada"] || 0, color: "bg-emerald-500" },
    { label: "Cerrados", value: counts["cerrado"] || 0, color: "bg-green-500" },
  ]
}

// ── Helpers de etiquetas legibles ──────────────────────────────

export const NICHO_LABELS: Record<string, string> = {
  climatizacion: "Climatización",
  instalaciones: "Instalaciones",
  energia: "Energía",
  otro: "Otro",
}

export const ESTADO_LABELS: Record<string, string> = {
  sin_contactar: "Sin contactar",
  contactado: "Contactado",
  respondio: "Respondió",
  interesado: "Interesado",
  demo_enviada: "Demo enviada",
  cerrado: "Cerrado",
  descartado: "Descartado",
}
